"""DIA-4 R1 — Reflection Context Core Contract."""
from .models import (
    CANONICAL_VERSION,
    CONTEXT_DIGEST_ALGORITHM_REVISION,
    CONTEXT_DOMAIN_SEPARATOR,
    DEFAULT_FACT_PROJECTION_REVISION,
    FACT_DIGEST_FUNCTION,
    POLICY_DOMAIN_SEPARATOR,
    SELECTION_ALGORITHM_REVISION,
    CanonicalFact,
    CanonicalFactReader,
    ContextAssemblyPolicy,
    ContextBounds,
    ContextFact,
    DeterministicReflectionContextAssembler,
    FactAuditMetadata,
    FactSemanticProvenance,
    ReflectionContext,
    ReflectionContextAssembler,
    ReflectionContextAudit,
    ReflectionOpportunityHandoff,
    ReflectionOpportunityInputPort,
)

__all__ = [
    "CANONICAL_VERSION",
    "CONTEXT_DIGEST_ALGORITHM_REVISION",
    "CONTEXT_DOMAIN_SEPARATOR",
    "DEFAULT_FACT_PROJECTION_REVISION",
    "FACT_DIGEST_FUNCTION",
    "POLICY_DOMAIN_SEPARATOR",
    "SELECTION_ALGORITHM_REVISION",
    "CanonicalFact",
    "CanonicalFactReader",
    "ContextAssemblyPolicy",
    "ContextBounds",
    "ContextFact",
    "DeterministicReflectionContextAssembler",
    "FactAuditMetadata",
    "FactSemanticProvenance",
    "ReflectionContext",
    "ReflectionContextAssembler",
    "ReflectionContextAudit",
    "ReflectionOpportunityHandoff",
    "ReflectionOpportunityInputPort",
]
