"""Reflection Trigger — Core semantic contract (DIA-3 R1.2 / Codex A)."""

from .models import (
    CANONICAL_VERSION,
    DOMAIN_SEPARATOR,
    EVIDENCE_DIGEST_FUNCTION,
    ActiveWindowState,
    ActivityWindowAnchor,
    BoundedSchedulingState,
    CausalAnchor,
    DeliveryTombstone,
    DeterministicTimerEligibilityBoundary,
    EligibilityBoundary,
    EventEligibilityBoundary,
    EvidenceBasis,
    OpportunityKey,
    PendingOpportunity,
    QuietWindowAnchor,
    RecentDedupKey,
    ReflectionOpportunity,
    SchedulingCursor,
    SingleEventAnchor,
    TriggerKind,
    TriggerPolicy,
    TriggerReason,
    TriggerSourceRef,
)
from .repository_protocol import ReflectionTriggerStateRepository, TriggerIdentityConflict

__all__ = [
    "CANONICAL_VERSION",
    "DOMAIN_SEPARATOR",
    "EVIDENCE_DIGEST_FUNCTION",
    "TriggerKind",
    "TriggerSourceRef",
    "TriggerReason",
    "EvidenceBasis",
    "EventEligibilityBoundary",
    "DeterministicTimerEligibilityBoundary",
    "EligibilityBoundary",
    "SingleEventAnchor",
    "ActivityWindowAnchor",
    "QuietWindowAnchor",
    "CausalAnchor",
    "OpportunityKey",
    "ReflectionOpportunity",
    "TriggerPolicy",
    "PendingOpportunity",
    "SchedulingCursor",
    "ActiveWindowState",
    "RecentDedupKey",
    "DeliveryTombstone",
    "BoundedSchedulingState",
    "ReflectionTriggerStateRepository",
    "TriggerIdentityConflict",
]
