"""Session Store — metadata, listing, auto-title generation.

Stores session metadata in ~/.julia/sessions.json.
Titles generated by LLM after 3+ turns.
"""

from __future__ import annotations

import json as _json
import logging
import time as _time
from pathlib import Path
from typing import Optional

logger = logging.getLogger("julia.store")

STORE_PATH = Path("/Users/admin/.julia/sessions.json")


class SessionStore:
    """Manages session metadata. Thin — no cognitive logic."""

    def __init__(self, path: Path = STORE_PATH):
        self._path = path
        self._path.parent.mkdir(parents=True, exist_ok=True)
        self._data: dict = self._load()

    def _load(self) -> dict:
        if self._path.exists():
            try:
                return _json.loads(self._path.read_text())
            except Exception as exc:
                import logging; logging.getLogger("julia.session_store").warning("Failed to load sessions.json: %s", exc)
        return {"sessions": {}}

    def save(self):
        self._path.write_text(_json.dumps(self._data, ensure_ascii=False, indent=2))

    def get(self, session_id: str) -> Optional[dict]:
        return self._data.get("sessions", {}).get(session_id)

    def ensure(self, session_id: str):
        sessions = self._data.setdefault("sessions", {})
        if session_id not in sessions:
            sessions[session_id] = {
                "id": session_id,
                "title": "",
                "created_at": _time.strftime("%Y-%m-%d %H:%M"),
                "updated_at": _time.strftime("%Y-%m-%d %H:%M"),
                "message_count": 0,
                "topics": [],
            }
            self.save()
        return sessions[session_id]

    def touch(self, session_id: str, topic: str = "", user_msg: str = "", assistant_msg: str = ""):
        meta = self.ensure(session_id)
        meta["updated_at"] = _time.strftime("%Y-%m-%d %H:%M")
        meta["message_count"] = meta.get("message_count", 0) + 1
        if topic and topic not in meta.get("topics", []):
            meta.setdefault("topics", []).append(topic)
            if len(meta["topics"]) > 10:
                meta["topics"] = meta["topics"][-10:]

        # CM-R1: shadow transcript retired. ConversationRuntime owns sole durable
        # transcript authority. SessionStore retains only derived catalog metadata.
        self.save()

    def set_title(self, session_id: str, title: str):
        meta = self.ensure(session_id)
        meta["title"] = title
        self.save()

    def delete(self, session_id: str):
        self._data.get("sessions", {}).pop(session_id, None)
        self.save()

    def list_all(self) -> list[dict]:
        """Return sessions sorted by last update, newest first."""
        sessions = self._data.get("sessions", {}).values()
        result = []
        for s in sessions:
            result.append({
                "id": s.get("id"),
                "title": s.get("title") or "新对话",
                "updated_at": s.get("updated_at"),
                "message_count": s.get("message_count", 0),
                "topics": s.get("topics", [])[-3:],
            })
        result.sort(key=lambda x: x.get("updated_at", ""), reverse=True)
        return result

    def generate_title(self, session_id: str, js) -> Optional[str]:
        """Use LLM to generate a session title from this session's messages."""
        meta = self.get(session_id)
        if not meta:
            return None

        # CM-R1: messages[] shadow transcript retired. Title generation now
        # relies on canonical ConversationRuntime transcript, not SessionStore.
        msgs = meta.get("messages", [])
        if not msgs:
            return None
        user_msgs = [m["content"][:80] for m in msgs if m.get("role") == "user"][:3]
        if len(user_msgs) < 1:
            return None

        prompt = f"""根据以下对话，生成一个简短的会话标题（8-15字）。只输出标题，不要说其他话。

对话: {' | '.join(user_msgs)}

标题:"""

        try:
            reply = js.provider.chat(
                [{"role": "user", "content": prompt}],
                cognitive_mode="engineering_collaboration"
            )
            title = reply.strip().strip('"').strip("'").strip("。").strip(".").strip()
            if 2 <= len(title) <= 25:
                self.set_title(session_id, title)
                return title
        except Exception as e:
            logger.warning(f"Title generation failed: {e}")
        return None


# ── Singleton ───────────────────────────────────────────────────────────────

_store: Optional[SessionStore] = None


def get_store() -> SessionStore:
    global _store
    if _store is None:
        _store = SessionStore()
    return _store
