"""Layer 2 + 3: Speech Prosody Planner + TTS Adapter.

Converts CognitiveEmotion → SpeechMetadata → TTS-specific parameters.
Emotion belongs to Julia Runtime. TTS only executes.
"""

from __future__ import annotations

from dataclasses import dataclass

from julia_core.voice_os.emotion_state import CognitiveEmotion, EmotionState


@dataclass(frozen=True, slots=True)
class SpeechMetadata:
    """Acoustic parameters — generated by Prosody Planner, consumed by TTS Adapter."""
    speed: float = 0.85         # 0.5-2.0  (mapped to Fish prosody.speed / Edge rate)
    pitch_shift: str = "+0Hz"   # e.g. "+3Hz", "-5%" (Edge pitch)
    pause_ms: int = 300         # mapped to SSML <break> or text padding
    energy: float = 0.7         # 0.0-1.0 (future: voice intensity)


# ── Emotion → Prosody mapping ──

_EMOTION_TO_PROSODY: dict[EmotionState, dict] = {
    EmotionState.WARM:       {"speed": 0.85, "pitch": "+3Hz",  "pause": 300, "energy": 0.6},
    EmotionState.THINKING:   {"speed": 0.72, "pitch": "-5Hz",  "pause": 500, "energy": 0.7},
    EmotionState.CONFIDENT:  {"speed": 0.88, "pitch": "+5Hz",  "pause": 350, "energy": 0.8},
    EmotionState.EXCITED:    {"speed": 1.05, "pitch": "+10Hz", "pause": 200, "energy": 0.9},
    EmotionState.SOFT:       {"speed": 0.75, "pitch": "-3Hz",  "pause": 400, "energy": 0.4},
    EmotionState.CONCERNED:  {"speed": 0.78, "pitch": "-2Hz",  "pause": 450, "energy": 0.55},
    EmotionState.PLAYFUL:    {"speed": 0.95, "pitch": "+8Hz",  "pause": 250, "energy": 0.75},
    EmotionState.NEUTRAL:    {"speed": 0.82, "pitch": "+0Hz",  "pause": 300, "energy": 0.6},
}


class SpeechProsodyPlanner:
    """Converts CognitiveEmotion → SpeechMetadata.

    Julia Runtime owns the emotion. This planner owns the mapping.
    TTS providers only receive the final SpeechMetadata.
    """

    _NEUTRAL_SPEED = 0.82
    _NEUTRAL_ENERGY = 0.6

    def plan(self, emotion: CognitiveEmotion | None = None) -> SpeechMetadata:
        if emotion is None:
            emotion = CognitiveEmotion()
        base = _EMOTION_TO_PROSODY.get(emotion.state, _EMOTION_TO_PROSODY[EmotionState.NEUTRAL])
        intensity = max(0.0, min(1.0, emotion.intensity))
        # Linear interpolation: neutral → emotion_base, driven by intensity
        speed = self._NEUTRAL_SPEED + (base["speed"] - self._NEUTRAL_SPEED) * intensity
        energy = self._NEUTRAL_ENERGY + (base["energy"] - self._NEUTRAL_ENERGY) * intensity
        return SpeechMetadata(
            speed=round(speed, 2),
            pitch_shift=base["pitch"],
            pause_ms=base["pause"],
            energy=round(energy, 2),
        )
